LEZER_ARGS :=
ifdef DEBUG
	LEZER_ARGS := --names $(LEZER_ARGS)
endif

# Written by humans
SRC = src/julia.grammar src/tokens.js

# Generated by lezer
PARSER = src/_parser.js src/_parser.terms.js

# Bundled by rollup
INDEX = dist/index.js dist/index.cjs


build: $(INDEX)
$(INDEX): $(PARSER)
	ROLLUP_IN="$(<)" \
	ROLLUP_OUT="dist/index" \
	npx rollup -c

$(PARSER): $(SRC)
	npx lezer-generator $(LEZER_ARGS) $(<) -o src/_parser


.PHONY: test check clean

test: $(INDEX) test/*
	npx mocha test/test-julia.js

check: # Ensure tooling is installed
	node --version
	npm --version

clean: # Remove generated files
	rm $(PARSER)
	rm $(INDEX)
